// Code generated by MockGen. DO NOT EDIT.
// Source: slug/slugger.go

// Package mock_slug is a generated GoMock package.
package mock_slug

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSlugger is a mock of Slugger interface.
type MockSlugger struct {
	ctrl     *gomock.Controller
	recorder *MockSluggerMockRecorder
}

// MockSluggerMockRecorder is the mock recorder for MockSlugger.
type MockSluggerMockRecorder struct {
	mock *MockSlugger
}

// NewMockSlugger creates a new mock instance.
func NewMockSlugger(ctrl *gomock.Controller) *MockSlugger {
	mock := &MockSlugger{ctrl: ctrl}
	mock.recorder = &MockSluggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlugger) EXPECT() *MockSluggerMockRecorder {
	return m.recorder
}

// GenerateSlug mocks base method.
func (m *MockSlugger) GenerateSlug(t string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSlug", t)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateSlug indicates an expected call of GenerateSlug.
func (mr *MockSluggerMockRecorder) GenerateSlug(t interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSlug", reflect.TypeOf((*MockSlugger)(nil).GenerateSlug), t)
}
